In [1]:
#### arrays, one d, 2 d arrays (matrices vectors)
#### tensors ##### accelerated over a gpu
import torch

In [5]:
torch.tensor([1,2,3]).shape

torch.Size([3])

In [4]:
torch.tensor([[1,2,3]]).shape

torch.Size([1, 3])

In [6]:
torch.tensor([1,2,3]).size()

torch.Size([3])

In [8]:
torch.zeros([1,2,2,3])

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])

In [10]:
torch.tensor([1,2]).tolist()

[1, 2]

In [12]:
torch.tensor([1,2,3]).numpy()

array([1, 2, 3])

In [14]:
device=torch.device("cuda" if torch.cuda.is_available() else 'cpu') #####

In [15]:
device

device(type='cpu')

In [16]:
torch.zeros([1,2,2,3]).to(device)

tensor([[[[0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.]]]])

In [17]:
#### Gradient descent (gradient matrix) 
torch.zeros([1,2,3],requires_grad=True)

tensor([[[0., 0., 0.],
         [0., 0., 0.]]], requires_grad=True)

Minmize $X^2+4X$

In [18]:
x=torch.tensor(0.0,requires_grad=True)

In [19]:
z=x*x+4*x ### forward pass

In [20]:
z.backward()

In [21]:
x.grad ### Grad of x at 0 wrt z

tensor(4.)

In [22]:
z=x*x+4*x

In [23]:
z.backward()

In [24]:
x.grad ### Start accumulating the value of gradients,
### Pass 1
### grad=4
### Pass 2
### grad_now+grad_prev=4+4=8


tensor(8.)

In [25]:
x.grad.zero_()

tensor(0.)

In [26]:
x.grad

tensor(0.)

In [27]:
### Forward pass
#### backward()
#### zero out the graidients
### xnew=xold-lr*(sum(grad))

In [30]:
x=torch.tensor(0.0,requires_grad=True)
lr=0.01
for i in range(10):
    z=x*x+4*x
    z.backward() ### dz/dx
    with torch.no_grad(): ##Disables any gradient computation
        x-=lr*x.grad
        x.grad.zero_()
    print(f"Z {z}, x: {x}")

Z 0.0, x: -0.03999999910593033
Z -0.15839999914169312, x: -0.07919999957084656
Z -0.31052735447883606, x: -0.11761599779129028
Z -0.4566304683685303, x: -0.15526367723941803
Z -0.5969479084014893, x: -0.19215840101242065
Z -0.7317087650299072, x: -0.22831523418426514
Z -0.8611330986022949, x: -0.2637489140033722
Z -0.9854321479797363, x: -0.29847392439842224
Z -1.104809045791626, x: -0.3325044512748718
Z -1.2194585800170898, x: -0.3658543527126312


In [34]:
### Autodiff
### xy=750=>x=750/y
## x+10y Minimize this
### 750/y+y*10

In [33]:
x=torch.tensor(1.0,requires_grad=True)
lr=0.01
for i in range(100):
    z=(750/x)+x*10
    z.backward()
    with torch.no_grad():
        x-=lr*x.grad
        x.grad.zero_()
    print(f"Z: {z}, x: {x}")

Z: 760.0, x: 8.399999618530273
Z: 173.2857208251953, x: 8.406291961669922
Z: 173.28179931640625, x: 8.41242504119873
Z: 173.27809143066406, x: 8.418403625488281
Z: 173.27456665039062, x: 8.42423152923584
Z: 173.27120971679688, x: 8.429913520812988
Z: 173.2680206298828, x: 8.435453414916992
Z: 173.26498413085938, x: 8.4408540725708
Z: 173.26211547851562, x: 8.446120262145996
Z: 173.25936889648438, x: 8.451254844665527
Z: 173.25677490234375, x: 8.45626163482666
Z: 173.25428771972656, x: 8.46114444732666
Z: 173.25193786621094, x: 8.465906143188477
Z: 173.24969482421875, x: 8.470550537109375
Z: 173.24755859375, x: 8.475079536437988
Z: 173.24554443359375, x: 8.479496955871582
Z: 173.2436065673828, x: 8.483805656433105
Z: 173.2417755126953, x: 8.488008499145508
Z: 173.24002075195312, x: 8.492108345031738
Z: 173.23837280273438, x: 8.496108055114746
Z: 173.23678588867188, x: 8.500009536743164
Z: 173.23529052734375, x: 8.503815650939941
Z: 173.23385620117188, x: 8.507528305053711
Z: 173.2324981

In [36]:
##### ML problem: 
import pandas as pd
reg=pd.read_csv("../sony/data/regression.csv")

In [37]:
reg.head(2)

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0        8.0         307.0       130.0  3504.0          12.0  70.0   
1  15.0        8.0         350.0       165.0  3693.0          11.5  70.0   

   origin  
0     1.0  
1     1.0

In [38]:
### mpg=b0+b1*cyl ## as a matrix product?

In [39]:
### dloss/db0, dloss/db1
#### loss=f(b0,b1)
##loss=eq
##loss.backward()
##b0.grad
##b1.grad
X=reg[['cylinders']].values
y=reg[['mpg']].values

In [40]:
## W dim?=> dloss/dW,dloss/db
W=torch.randn(1,1,requires_grad=True)
b=torch.randn(1,requires_grad=True)

In [ ]:
### loss?
loss=sum((y-XW+b)^2)/n
loss.backward()
W.grad
b.grad

In [41]:
X=torch.tensor(X)
y=torch.tensor(y)

In [45]:
lr=0.01
for i in range(100):
    diff=y-torch.matmul(X.float(),W)+b
    loss=sum(diff*diff)/y.shape[0]
    loss.backward()
    with torch.no_grad():
        W-=lr*W.grad
        b-=lr*b.grad
        W.grad.zero_()
        b.grad.zero_()
    print(f"Loss: {loss.item()}, W: {W.detach().numpy()}, b: {b.detach().numpy()}")

Loss: 106.57937383717696, W: [[1.5394461]], b: [-12.498031]
Loss: 106.29652724282161, W: [[1.5306689]], b: [-12.550415]
Loss: 106.01465406982496, W: [[1.5219065]], b: [-12.602709]
Loss: 105.73375239029292, W: [[1.5131594]], b: [-12.654913]
Loss: 105.4538148533757, W: [[1.5044272]], b: [-12.707027]
Loss: 105.17483884401985, W: [[1.4957101]], b: [-12.759052]
Loss: 104.8968210069427, W: [[1.4870082]], b: [-12.810987]
Loss: 104.61976103636141, W: [[1.4783207]], b: [-12.862833]
Loss: 104.34365403355959, W: [[1.4696487]], b: [-12.91459]
Loss: 104.06849371735905, W: [[1.4609914]], b: [-12.966257]
Loss: 103.79428275126844, W: [[1.452349]], b: [-13.017836]
Loss: 103.52101361310103, W: [[1.4437215]], b: [-13.069325]
Loss: 103.24868271208203, W: [[1.4351087]], b: [-13.120727]
Loss: 102.97728938506957, W: [[1.426511]], b: [-13.17204]
Loss: 102.70682585822372, W: [[1.417928]], b: [-13.223265]
Loss: 102.43729364242495, W: [[1.4093596]], b: [-13.274402]
Loss: 102.16868574302856, W: [[1.4008062]], b: 

In [ ]:
### linear classifier.
### Can you estimate a linear classifier using autodiff
### Loss for linear classifier?